from sqlalchemy import Column, Integer, String, BigInteger, VARCHAR, Float
from .database import Base
class DictMixIn:
    def to_dict(self):
        return {
            column.name: getattr(self, column.name)
            if not isinstance(getattr(self, column.name), datetime.datetime)
            else getattr(self, column.name).isoformat()
            for column in self.__table__.columns
        }
    
class Players(Base, DictMixIn):
    __tablename__ = 'players'
    PID = Column(String(25), primary_key=True)
    Name = Column(String(25))
    Position = Column(String)
    Team = Column(String)


##this table defines player pool for the week 
class SS_Data(Base, DictMixIn):
    __tablename__ = 'Saber_Sim_Data'
#     PID = Column(String, ForeignKey('players.PID'))
    Name = Column(String(30))
    Team = Column(String(10))
    Opponent = Column(String(10))
    Position = Column(String(5))
    Projection = Column(Float)
    Actual = Column(String)
    Price = Column(BigInteger)
    Value = Column(Float)
#     ## added by me to keep track of week/Season
#     Date_Added = Column(Date) 
#     Week = Column(Integer)
#     Season = Column(Integer)
#     ## end of added data points
    proj_own = Column(Float)
    dk_point = Column(Float)
    dk_25_percentile = Column(Float)
    dk_50_percentile  = Column(Float)
    dk_75_percentile = Column(Float) 
    dk_85_percentile = Column(Float)
    dk_95_percentile = Column(Float) 
    dk_99_percentile = Column(Float)  
    fd_points = Column(Float) 
    fd_25_percentile = Column(Float)
    fd_50_percentile = Column(Float) 
    fd_75_percentile = Column(Float) 
    fd_85_percentile = Column(Float)
    fd_95_percentile  = Column(Float)
    fd_99_percentile = Column(Float) 
    fdraft_points = Column(Float)
    fdraft_25_percentile = Column(Float) 
    fdraft_50_percentile = Column(Float) 
    fdraft_75_percentile = Column(Float)
    fdraft_85_percentile = Column(Float) 
    fdraft_95_percentile = Column(Float) 
    fdraft_99_percentile = Column(Float)
    yahoo_points = Column(Float)
    yahoo_25_percentile = Column(Float) 
    yahoo_50_percentile = Column(Float)
    yahoo_75_percentile = Column(Float) 
    yahoo_85_percentile = Column(Float) 
    yahoo_95_percentile = Column(Float)
    yahoo_99_percentile = Column(Float)
    dk_std = Column(Float)
    fd_std = Column(Float)
    fdraft_std = Column(Float)
    yahoo_std = Column(Float)
    pass_attempts = Column(Float)
    completions = Column(Float)
    passing_yards = Column(Float)
    passing_td = Column(Float)
    receptions = Column(Float)
    receiving_yards = Column(Float)
    receiving_td = Column(Float)
    rushes = Column(Float)
    rushing_yards = Column(Float)
    rushing_td = Column(Float)
    
class _4f4_Proj(Base, DictMixIn):
    __tablename__ = '4for4_Projections'
    PID = Column(Column, foreign_key=True)
    Season  = Column(Integer)
    Week = Column(Integer)
    PID = Column(String(20))
    Player = Column(String(20))
    Pos = Column(String(20))
    Team = Column(String(20))
    Opp = Column(String(20))
    aFPA = Column(Float)
    aFPA_Rk = Column(Integer)
    FFPts = Column(Float)
    Comp = Column(Float)
    Pass_Att = Column(Float)
    Pass_Yds = Column(Float)
    Pass_TD = Column(Float)
    INT = Column(Float)
    Rush_Att = Column(Float)
    Rush_Yds = Column(Float)
    Rush_TD = Column(Float)
    Rec = Column(Float)
    Rec_Yds = Column(Float)
    Rec_TD = Column(Float)
    Pa1D = Column(Float)
    Ru1D = Column(Float)
    Rec1D = Column(Float)
    Fum = Column(Float)
    XP = Column(Float)
    FG = Column(Float)
    Grade = Column(String)
    
class _4f4_Ceiling(Base, DictMixIn):
    __tablename__ = '4for4_Ceiling'
    PID = Column(Column, foreign_key=True)
    Season = Column(Integer)
    Week = Column(Integer)
    PID = Column(Integer)
    Player = Column(String(30))
    Pos = Column(String(30))
    Team = Column(String(30))
    Opp = Column(String(30))
    aFPA = Column(Float)
    aFPA_Rk = Column(Integer)
    FFPts = Column(Float)
    Comp = Column(Float)
    Pass_Att = Column(Float)
    Pass_Yds = Column(Float)
    Pass_TD = Column(Float)
    INT = Column(Float)
    Rush_Att = Column(Float)
    Rush_Yds = Column(Float)
    Rush_TD = Column(Float)
    Rec = Column(Float)
    Rec_Yds = Column(Float)
    Rec_TD = Column(Float)
    Pa1D = Column(Float)
    Ru1D = Column(Float)
    Rec1D = Column(Float)
    Fum = Column(Float)
    XP = Column(Float)
    FG = Column(Float)
    Grade = Column(Integer)
    DK_Proj = Column(Float)
    DK_Price = Column(Float)
    DK_Val = Column(Float)
    DK_Pts_per_1k = Column(Float)
    DK_Flr = Column(Float)
    DK_Flr_Val = Column(Float)
    DK_Flr_per_1k = Column(Float)
    DK_Ceil = Column(Float)
    DK_Ceil_Val = Column(Float)
    DK_Ceil_per_1k = Column(Float)
    DK_Wk_Change = Column(Integer)
    DK_Own_Percent = Column(Integer)
    FD_Proj = Column(Float)
    FD_Price = Column(Float)
    FD_Val = Column(Float)
    FD_Pts_pr_1k = Column(Float)
    FD_Flr = Column(Float)
    FD_Flr_Val = Column(Float)
    FD_Flr_pr_1k = Column(Float)
    FD_Ceil = Column(Float)
    FD_Ceil_Val = Column(Float)
    FD_Ceil_pr_1k = Column(Float)
    FD_Wk_Change = Column(String)
    FD_Own_Percent = Column(String)
    Y_Proj = Column(Float)
    Y_Price = Column(Float)
    Y_Val = Column(Float)
    Y_Pt_pr_Dollar = Column(Float)
    Y_Flr = Column(Float)
    Y_Flr_Val = Column(Float)
    Y_Floor_pr_Dollar = Column(Float)
    Y_Ceil = Column(Float)
    Y_Ceil_Val = Column(Float)
    Y_Ceil_pr_Dollar = Column(Float)
    Y_Wk_Change = Column(Integer)
    FyD_Proj = Column(Float)
    FyD_Price = Column(Float)
    FyD_Val = Column(Float)
    FyD_Pt_pr_1k = Column(Float)
    FyD_Flr = Column(Float)
    FyD_Flr_Val = Column(Float)
    FyD_Flr_pr_1k = Column(Float)
    FyD_Ceil = Column(Float)
    FyD_Ceil_Val = Column(Float)
    FyD_Ceil_pr_1k = Column(Float)
    FyD_Wk_Change = Column(String)
    O_U = Column(Float)
    Line = Column(Float)
    Team_O_U = Column(Float)

class _4f4_wrcb:
    __tablename__ = '4for4_WRCB'
    Player = Column(String)
    Team = Column(String)
    Opponent = Column(String)
    Matchup = Column(String)
    Shadow = Column(String)

class _4f4_RedZ:
    __tablename__ = '4f4_RedZone_Data'
    Season = Column(Integer) 
    Week = Column(Float) 
    PID = Column(String) 
    Player = Column(String) 
    Pos = Column(String) 
    Team = Column(String) 
    Opp = Column(String) 
    aFPA = Column(Float) 
    aFPA Rk = Column(Float) 
    FFPts = Column(Float) 
    Comp = Column(Float) 
    Pass Att = Column(Float) 
    Pass Yds = Column(Float) 
    Pass TD = Column(Float) 
    INT = Column(Float) 
    Rush Att = Column(Float) 
    Rush Yds = Column(Float) 
    Rush TD = Column(Float) 
    Rec = Column(Float) 
    Rec Yds = Column(Float) 
    Rec TD = Column(Float) 
    Pa1D = Column(Float) 
    Ru1D = Column(Float) 
    Rec1D = Column(Float) 
    Fum = Column(Float) 
    XP = Column(Float) 
    FG = Column(Float) 
    Grade = Column(String) 
    DK (Proj) = Column(Float) 
    DK ($) = Column(Float) 
    DK (Val) = Column(Float) 
    DK (Pt/$1k) = Column(Float) 
    DK (Flr) = Column(Float) 
    DK (Flr Val) = Column(Float) 
    DK (Flr/$1k) = Column(Float) 
    DK (Ceil) = Column(Float) 
    DK (Ceil Val) = Column(Float) 
    DK (Ceil/$1k) = Column(Float) 
    DK (Wk $ Chg) = Column(Integer) 
    DK (Own %) = Column(Integer) 
    FD (Proj) = Column(Float) 
    FD ($) = Column(Float) 
    FD (Val) = Column(Float) 
    FD (Pt/$1k) = Column(Float) 
    FD (Flr) = Column(Float) 
    FD (Flr Val) = Column(Float) 
    FD (Flr/$1k) = Column(Float) 
    FD (Ceil) = Column(Float) 
    FD (Ceil Val) = Column(Float) 
    FD (Ceil/$1k) = Column(Float) 
    FD (Wk $ Chg) = Column(Integer) 
    FD (Own %) = Column(Integer) 
    Y! (Proj) = Column(Float) 
    Y! ($) = Column(Float) 
    Y! (Val) = Column(Float) 
    Y! (Pt/$) = Column(Float) 
    Y! (Flr) = Column(Float) 
    Y! (Flr Val) = Column(Float) 
    Y! (Floor/$) = Column(Float) 
    Y! (Ceil) = Column(Float) 
    Y! (Ceil Val) = Column(Float) 
    Y! (Ceil/$) = Column(Float) 
    Y! (Wk $ Chg) = Column(Integer) 
    FyD (Proj) = Column(Float) 
    FyD ($) = Column(Float) 
    FyD (Val) = Column(Float) 
    FyD (Pt/$1k) = Column(Float) 
    FyD (Flr) = Column(Float) 
    FyD (Flr Val) = Column(Float) 
    FyD (Flr/$1k) = Column(Float) 
    FyD (Ceil) = Column(Float) 
    FyD (Ceil Val) = Column(Float) 
    FyD (Ceil/$1k) = Column(Float) 
    FyD (Wk $ Chg)     object
    O/U = Column(Float) 
    Line = Column(Float) 
    Team O/U = Column(Float) 

class _4f4_WR_fp:
    __tablename__ = '4for4_WR_fantasy_points'
    Player = Column(String) 
    Pos = Column(String) 
    Team = Column(String) 
    G = Column(Integer) 
    W5 = Column(Float) 
    W6 = Column(Float) 
    W7 = Column(Float) 
    W8 = Column(Float) 
    DK_Pts = Column(Float) 
    DK_Pts_pr_G = Column(Float) 

class _4f4_RB_fp:
    __tablename__ = '4for4_RB_fantasy_points'
    Player = Column(String) 
    Pos = Column(String) 
    Team = Column(String) 
    G = Column(Integer) 
    W13 = Column(Float) 
    W14 = Column(Float) 
    W15 = Column(Float) 
    DK_Pts = Column(Float) 
    DK_Pts_pr_G = Column(Float) 

class _4f4_RB_tar:
    __tablename__ = '4for4_RB_target'
    Player     object
    Pos = Column(String) 
    Team = Column(String) 
    G = Column(Integer) 
    W13 = Column(Float) 
    W14 = Column(Float) 
    W15 = Column(Float) 
    TGTs = Column(Integer) 
    TGTs_pr_G = Column(Float) 
    Array = Column(Float) 

class AirY_WR:
    __tablename__ = 'AirY_WR'
    full_name     object
    position = Column(String) 
    team = Column(String) 
    targets = Column(Float) 
    rec = Column(Float) 
    rec_yards = Column(Float) 
    air_yards = Column(Float) 
    yac = Column(Float) 
    td = Column(Float) 
    adot = Column(Float) 
    racr = Column(Float) 
    ms_air = Column(Float) 
    tgt_share = Column(Float) 
    wopr = Column(Float) 
    ppr = Column(Float) 
    Tar_pr_Gam = Column(Float) 
    AY_pr_Gam = Column(Float) 

class AirY_TE:
    __tablename__ = 'AirY_TE'
    full_name     object
    position = Column(String) 
    team = Column(String) 
    targets = Column(Float) 
    rec = Column(Float) 
    rec_yards = Column(Float) 
    air_yards = Column(Float) 
    yac = Column(Float) 
    td = Column(Float) 
    adot = Column(Float) 
    racr = Column(Float) 
    ms_air = Column(Float) 
    tgt_share = Column(Float) 
    wopr = Column(Float) 
    ppr = Column(Float) 
    Tar_pr_3 = Column(Float) 

class ETR_Ceiling:
    __tablename__ = 'ETR_Ceiling'
    Season = Column(Integer) 
    Week = Column(Integer) 
    PID = Column(String) 
    Player = Column(String) 
    Pos = Column(String) 
    Team = Column(String) 
    Opp = Column(String) 
    aFPA = Column(Float) 
    aFPA Rk = Column(Integer) 
    FFPts = Column(Float) 
    Comp = Column(Float) 
    Pass Att = Column(Float) 
    Pass Yds = Column(Float) 
    Pass TD = Column(Float) 
    INT = Column(Float) 
    Rush Att = Column(Float) 
    Rush Yds = Column(Float) 
    Rush TD = Column(Float) 
    Rec = Column(Float) 
    Rec Yds = Column(Float) 
    Rec TD = Column(Float) 
    Pa1D = Column(Float) 
    Ru1D = Column(Float) 
    Rec1D = Column(Float) 
    Fum = Column(Float) 
    XP = Column(Float) 
    FG = Column(Float) 
    Grade = Column(String) 
    DK (Proj) = Column(Float) 
    DK ($) = Column(Float) 
    DK (Val) = Column(Float) 
    DK (Pt/$1k) = Column(Float) 
    DK (Flr) = Column(Float) 
    DK (Flr Val) = Column(Float) 
    DK (Flr/$1k) = Column(Float) 
    DK (Ceil) = Column(Float) 
    DK (Ceil Val) = Column(Float) 
    DK (Ceil/$1k) = Column(Float) 
    DK (Wk $ Chg) = Column(Integer) 
    DK (Own %) = Column(Integer) 
    FD (Proj) = Column(Float) 
    FD ($) = Column(Float) 
    FD (Val) = Column(Float) 
    FD (Pt/$1k) = Column(Float) 
    FD (Flr) = Column(Float) 
    FD (Flr Val) = Column(Float) 
    FD (Flr/$1k) = Column(Float) 
    FD (Ceil) = Column(Float) 
    FD (Ceil Val) = Column(Float) 
    FD (Ceil/$1k) = Column(Float) 
    FD (Wk $ Chg) = Column(Integer) 
    FD (Own %) = Column(Integer) 
    Y! (Proj) = Column(Float) 
    Y! ($) = Column(Float) 
    Y! (Val) = Column(Float) 
    Y! (Pt/$) = Column(Float) 
    Y! (Flr) = Column(Float) 
    Y! (Flr Val) = Column(Float) 
    Y! (Floor/$) = Column(Float) 
    Y! (Ceil) = Column(Float) 
    Y! (Ceil Val) = Column(Float) 
    Y! (Ceil/$) = Column(Float) 
    Y! (Wk $ Chg) = Column(Integer) 
    FyD (Proj) = Column(Float) 
    FyD ($) = Column(Float) 
    FyD (Val) = Column(Float) 
    FyD (Pt/$1k) = Column(Float) 
    FyD (Flr) = Column(Float) 
    FyD (Flr Val) = Column(Float) 
    FyD (Flr/$1k) = Column(Float) 
    FyD (Ceil) = Column(Float) 
    FyD (Ceil Val) = Column(Float) 
    FyD (Ceil/$1k) = Column(Float) 
    FyD (Wk $ Chg)     object
    O/U = Column(Float) 
    Line = Column(Float) 
    Team O/U = Column(Float) 