from sqlalchemy import Column, Integer, String, BigInteger, VARCHAR, Float
from .database import Base


class DictMixIn:
    def to_dict(self):
        return {
            column.name: getattr(self, column.name)
            if not isinstance(getattr(self, column.name), datetime.datetime)
            else getattr(self, column.name).isoformat()
            for column in self.__table__.columns
        }
    
class Players(Base, DictMixIn):
    __tablename__ = 'players'
    PID = Column(String(25), primary_key=True)
    Name = Column(String(25))
    Position = Column(String)
    Team = Column(String)
    
class SS_Data(Base, DictMixIn):
    __tablename__ = 'Saber_Sim_Data'
#     PID = Column(String, ForeignKey('players.PID'))
    Name = Column(String(30), primary_key=True)
    Team = Column(String(10), primary_key=True)
    Opponent = Column(String(10), primary_key=True)
    Position = Column(String(5), primary_key=True)
    Projection = Column(Float, primary_key=True)
    Actual = Column(String)
    Price = Column(BigInteger)
    Value = Column(Float)
#     ## added by me to keep track of week/Season
#     Date_Added = Column(Date) 
#     Week = Column(Integer)
#     Season = Column(Integer)
#     ## end of added data points
    proj_own = Column(Float)
    dk_point = Column(Float)
    dk_25_percentile = Column(Float)
    dk_50_percentile  = Column(Float)
    dk_75_percentile = Column(Float) 
    dk_85_percentile = Column(Float)
    dk_95_percentile = Column(Float) 
    dk_99_percentile = Column(Float)  
    fd_points = Column(Float) 
    fd_25_percentile = Column(Float)
    fd_50_percentile = Column(Float) 
    fd_75_percentile = Column(Float) 
    fd_85_percentile = Column(Float)
    fd_95_percentile  = Column(Float)
    fd_99_percentile = Column(Float) 
    fdraft_points = Column(Float)
    fdraft_25_percentile = Column(Float) 
    fdraft_50_percentile = Column(Float) 
    fdraft_75_percentile = Column(Float)
    fdraft_85_percentile = Column(Float) 
    fdraft_95_percentile = Column(Float) 
    fdraft_99_percentile = Column(Float)
    yahoo_points = Column(Float)
    yahoo_25_percentile = Column(Float) 
    yahoo_50_percentile = Column(Float)
    yahoo_75_percentile = Column(Float) 
    yahoo_85_percentile = Column(Float) 
    yahoo_95_percentile = Column(Float)
    yahoo_99_percentile = Column(Float)
    dk_std = Column(Float)
    fd_std = Column(Float)
    fdraft_std = Column(Float)
    yahoo_std = Column(Float)
    pass_attempts = Column(Float)
    completions = Column(Float)
    passing_yards = Column(Float)
    passing_td = Column(Float)
    receptions = Column(Float)
    receiving_yards = Column(Float)
    receiving_td = Column(Float)
    rushes = Column(Float)
    rushing_yards = Column(Float)
    rushing_td = Column(Float)
    
class _4f4_Proj(Base, DictMixIn):
    __tablename__ = '4for4_Projections'
    Season = Column(Integer, primary_key=True)
    Week = Column(Integer, primary_key=True)
    PID = Column(String(20), primary_key=True)
    Player = Column(String(20), primary_key=True)
    Pos = Column(String(20), primary_key=True)
    Team = Column(String(20), primary_key=True)
    Opp = Column(String(20))
    aFPA = Column(Float)
    aFPA_Rk = Column(Integer)
    FFPts = Column(Float)
    Comp = Column(Float)
    Pass_Att = Column(Float)
    Pass_Yds = Column(Float)
    Pass_TD = Column(Float)
    INT = Column(Float)
    Rush_Att = Column(Float)
    Rush_Yds = Column(Float)
    Rush_TD = Column(Float)
    Rec = Column(Float)
    Rec_Yds = Column(Float)
    Rec_TD = Column(Float)
    Pa1D = Column(Float)
    Ru1D = Column(Float)
    Rec1D = Column(Float)
    Fum = Column(Float)
    XP = Column(Float)
    FG = Column(Float)
    Grade = Column(String)
    
class _4f4_Ceiling(Base, DictMixIn):
    __tablename__ = '4for4_Ceiling'
    Season = Column(Integer, primary_key=True)
    Week = Column(Integer, primary_key=True)
    PID = Column(Integer, primary_key=True)
    Player = Column(String(30), primary_key=True)
    Pos = Column(String(30), primary_key=True)
    Team = Column(String(30), primary_key=True)
    Opp = Column(String(30))
    aFPA = Column(Float)
    aFPA_Rk = Column(Integer)
    FFPts = Column(Float)
    Comp = Column(Float)
    Pass_Att = Column(Float)
    Pass_Yds = Column(Float)
    Pass_TD = Column(Float)
    INT = Column(Float)
    Rush_Att = Column(Float)
    Rush_Yds = Column(Float)
    Rush_TD = Column(Float)
    Rec = Column(Float)
    Rec_Yds = Column(Float)
    Rec_TD = Column(Float)
    Pa1D = Column(Float)
    Ru1D = Column(Float)
    Rec1D = Column(Float)
    Fum = Column(Float)
    XP = Column(Float)
    FG = Column(Float)
    Grade = Column(Integer)
    DK_Proj = Column(Float)
    DK_Price = Column(Float)
    DK_Val = Column(Float)
    DK_Pts_per_1k = Column(Float)
    DK_Flr = Column(Float)
    DK_Flr_Val = Column(Float)
    DK_Flr_per_1k = Column(Float)
    DK_Ceil = Column(Float)
    DK_Ceil_Val = Column(Float)
    DK_Ceil_per_1k = Column(Float)
    DK_Wk_Change = Column(Integer)
    DK_Own_Percent = Column(Integer)
    FD_Proj = Column(Float)
    FD_Price = Column(Float)
    FD_Val = Column(Float)
    FD_Pts_pr_1k = Column(Float)
    FD_Flr = Column(Float)
    FD_Flr_Val = Column(Float)
    FD_Flr_pr_1k = Column(Float)
    FD_Ceil = Column(Float)
    FD_Ceil_Val = Column(Float)
    FD_Ceil_pr_1k = Column(Float)
    FD_Wk_Change = Column(String)
    FD_Own_Percent = Column(String)
    Y_Proj = Column(Float)
    Y_Price = Column(Float)
    Y_Val = Column(Float)
    Y_Pt_pr_Dollar = Column(Float)
    Y_Flr = Column(Float)
    Y_Flr_Val = Column(Float)
    Y_Flr_pr_Dollar = Column(Float)
    Y_Ceil = Column(Float)
    Y_Ceil_Val = Column(Float)
    Y_Ceil_pr_Dollar = Column(Float)
    Y_Wk_Change = Column(Integer)
    FyD_Proj = Column(Float)
    FyD_Price = Column(Float)
    FyD_Val = Column(Float)
    FyD_Pt_pr_1k = Column(Float)
    FyD_Flr = Column(Float)
    FyD_Flr_Val = Column(Float)
    FyD_Flr_pr_1k = Column(Float)
    FyD_Ceil = Column(Float)
    FyD_Ceil_Val = Column(Float)
    FyD_Ceil_pr_1k = Column(Float)
    FyD_Wk_Change = Column(String)
    O_U = Column(Float)
    Line = Column(Float)
    Team_O_U = Column(Float)

    
class _4f4_WR_cb(Base, DictMixIn):
    __tablename__ = '4for4_WRCB'
    Player = Column(String, primary_key=True)
    Team = Column(String, primary_key=True)
    Opponent = Column(String, primary_key=True)
    Matchup = Column(String)
    Shadow = Column(String)

class _4f4_RedZ(Base, DictMixIn):
    __tablename__ = '4f4_RedZone_Data'
    Season = Column(Integer, primary_key=True) 
    Week = Column(Float, primary_key=True) 
    PID = Column(String, primary_key=True) 
    Player = Column(String, primary_key=True) 
    Pos = Column(String, primary_key=True) 
    Team = Column(String) 
    Opp = Column(String) 
    aFPA = Column(Float) 
    aFPA_Rk = Column(Float) 
    FFPts = Column(Float) 
    Comp = Column(Float) 
    Pass_Att = Column(Float) 
    Pass_Yds = Column(Float) 
    Pass_TD = Column(Float) 
    INT = Column(Float) 
    Rush_Att = Column(Float) 
    Rush_Yds = Column(Float) 
    Rush_TD = Column(Float) 
    Rec = Column(Float) 
    Rec_Yds = Column(Float) 
    Rec_TD = Column(Float) 
    Pa1D = Column(Float) 
    Ru1D = Column(Float) 
    Rec1D = Column(Float) 
    Fum = Column(Float) 
    XP = Column(Float) 
    FG = Column(Float) 
    Grade = Column(String) 
    DK_proj = Column(Float) 
    DK_price = Column(Float) 
    DK_val = Column(Float) 
    DK_PT_pr_1k = Column(Float) 
    DK_Flr = Column(Float) 
    DK_Flr_Val = Column(Float) 
    DK_Flr_pr_1k = Column(Float) 
    DK_Ceil = Column(Float) 
    DK_Ceil_Val = Column(Float) 
    DK_Ceil_pr_1k = Column(Float) 
    DK_Wk_Change = Column(Integer) 
    DK_own_percent = Column(Integer) 
    FD_proj = Column(Float) 
    FD_price = Column(Float) 
    FD_val = Column(Float) 
    FD_PT_pr_1k = Column(Float) 
    FD_Flr = Column(Float) 
    FD_Flr_Val = Column(Float) 
    FD_Flr_pr_1k = Column(Float) 
    FD_Ceil = Column(Float) 
    FD_Ceil_Val = Column(Float) 
    FD_Ceil_pr_1k = Column(Float) 
    FD_Wk_Change = Column(Integer) 
    FD_own_percent = Column(Integer) 
    Y_proj = Column(Float) 
    Y_price = Column(Float) 
    Y_val = Column(Float) 
    Y_Pt_pr_Dollar = Column(Float) 
    Y_Flr = Column(Float) 
    Y_Flr_Val = Column(Float) 
    Y_Flr_pr_Dollar = Column(Float) 
    Y_Ceil = Column(Float) 
    Y_Ceil_Val = Column(Float) 
    Y_Ceil_pr_Dollar = Column(Float) 
    Y_Wk_Change = Column(Integer) 
    FyD_proj = Column(Float) 
    FyD_price = Column(Float) 
    FyD_val = Column(Float) 
    FyD_PT_pr_1k = Column(Float) 
    FyD_Flr = Column(Float) 
    FyD_Flr_Val = Column(Float) 
    FyD_Flr_pr_1k = Column(Float) 
    FyD_Ceil = Column(Float) 
    FyD_Ceil_Val = Column(Float) 
    FyD_Ceil_pr_1k = Column(Float) 
    FyD_Wk_Change = Column(Integer)
    O_U = Column(Float) 
    Line = Column(Float) 
    Team_O_U = Column(Float) 

class _4f4_WR_fp(Base, DictMixIn):
    __tablename__ = '4for4_WR_fantasy_points'
    Player = Column(String, primary_key=True) 
    Pos = Column(String, primary_key=True) 
    Team = Column(String, primary_key=True) 
    G = Column(Integer) 
    W5 = Column(Float) 
    W6 = Column(Float) 
    W7 = Column(Float) 
    W8 = Column(Float) 
    DK_Pts = Column(Float) 
    DK_Pts_pr_G = Column(Float) 

class _4f4_RB_fp(Base, DictMixIn):
    __tablename__ = '4for4_RB_fantasy_points'
    Player = Column(String, primary_key=True) 
    Pos = Column(String, primary_key=True) 
    Team = Column(String, primary_key=True) 
    G = Column(Integer) 
    W13 = Column(Float) 
    W14 = Column(Float) 
    W15 = Column(Float) 
    DK_Pts = Column(Float) 
    DK_Pts_pr_G = Column(Float) 

class _4f4_RB_tar(Base, DictMixIn):
    __tablename__ = '4for4_RB_target'
    Player = Column(String, primary_key=True)
    Pos = Column(String, primary_key=True) 
    Team = Column(String, primary_key=True) 
    G = Column(Integer) 
    W13 = Column(Float) 
    W14 = Column(Float) 
    W15 = Column(Float) 
    TGTs = Column(Integer) 
    TGTs_pr_G = Column(Float) 
    Array = Column(Float) 

class AirY_WR(Base, DictMixIn):
    __tablename__ = 'AirY_WR'
    full_name = Column(String, primary_key=True)
    position = Column(String, primary_key=True) 
    team = Column(String, primary_key=True) 
    targets = Column(Float, primary_key=True) 
    rec = Column(Float) 
    rec_yards = Column(Float) 
    air_yards = Column(Float) 
    yac = Column(Float) 
    td = Column(Float) 
    adot = Column(Float) 
    racr = Column(Float) 
    ms_air = Column(Float) 
    tgt_share = Column(Float) 
    wopr = Column(Float) 
    ppr = Column(Float) 
    Tar_pr_Gam = Column(Float) 
    AY_pr_Gam = Column(Float) 

class AirY_TE(Base, DictMixIn):
    __tablename__ = 'AirY_TE'
    full_name = Column(String, primary_key=True)
    position = Column(String, primary_key=True) 
    team = Column(String, primary_key=True) 
    targets = Column(Float) 
    rec = Column(Float) 
    rec_yards = Column(Float) 
    air_yards = Column(Float) 
    yac = Column(Float) 
    td = Column(Float) 
    adot = Column(Float) 
    racr = Column(Float) 
    ms_air = Column(Float) 
    tgt_share = Column(Float) 
    wopr = Column(Float) 
    ppr = Column(Float) 
    Tar_pr_3 = Column(Float) 

class ETR_Ceil(Base, DictMixIn):
    __tablename__ = 'ETR_Ceiling'
    Season = Column(Integer, primary_key=True) 
    Week = Column(Integer, primary_key=True) 
    PID = Column(String, primary_key=True) 
    Player = Column(String, primary_key=True) 
    Pos = Column(String, primary_key=True) 
    Team = Column(String) 
    Opp = Column(String) 
    aFPA = Column(Float) 
    aFPA_Rk = Column(Integer) 
    FFPts = Column(Float) 
    Comp = Column(Float) 
    Pass_Att = Column(Float) 
    Pass_Yds = Column(Float) 
    Pass_TD = Column(Float) 
    INT = Column(Float) 
    Rush_Att = Column(Float) 
    Rush_Yds = Column(Float) 
    Rush_TD = Column(Float) 
    Rec = Column(Float) 
    Rec_Yds = Column(Float) 
    Rec_TD = Column(Float) 
    Pa1D = Column(Float) 
    Ru1D = Column(Float) 
    Rec1D = Column(Float) 
    Fum = Column(Float) 
    XP = Column(Float) 
    FG = Column(Float) 
    Grade = Column(String) 
    DK_proj = Column(Float) 
    DK_price = Column(Float) 
    DK_val = Column(Float) 
    DK_PT_pr_1k = Column(Float) 
    DK_Flr = Column(Float) 
    DK_Flr_Val = Column(Float) 
    DK_Flr_pr_1k = Column(Float) 
    DK_Ceil = Column(Float) 
    DK_Ceil_Val = Column(Float) 
    DK_Ceil_pr_1k = Column(Float) 
    DK_Wk_Change = Column(Integer) 
    DK_own_percent = Column(Integer) 
    FD_proj = Column(Float) 
    FD_price = Column(Float) 
    FD_val = Column(Float) 
    FD_PT_pr_1k = Column(Float) 
    FD_Flr = Column(Float) 
    FD_Flr_Val = Column(Float) 
    FD_Flr_pr_1k = Column(Float) 
    FD_Ceil = Column(Float) 
    FD_Ceil_Val = Column(Float) 
    FD_Ceil_pr_1k = Column(Float) 
    FD_Wk_Change = Column(Integer) 
    FD_own_percent = Column(Integer) 
    Y_proj = Column(Float) 
    Y_price = Column(Float) 
    Y_val = Column(Float) 
    Y_Pt_pr_Dollar = Column(Float) 
    Y_Flr = Column(Float) 
    Y_Flr_Val = Column(Float) 
    Y_Flr_pr_Dollar = Column(Float) 
    Y_Ceil = Column(Float) 
    Y_Ceil_Val = Column(Float) 
    Y_Ceil_pr_Dollar = Column(Float) 
    Y_Wk_Change = Column(Integer) 
    FyD_proj = Column(Float) 
    FyD_price = Column(Float) 
    FyD_val = Column(Float) 
    FyD_PT_pr_1k = Column(Float) 
    FyD_Flr = Column(Float) 
    FyD_Flr_Val = Column(Float) 
    FyD_Flr_pr_1k = Column(Float) 
    FyD_Ceil = Column(Float) 
    FyD_Ceil_Val = Column(Float) 
    FyD_Ceil_pr_1k = Column(Float) 
    FyD_Wk_Change = Column(Integer)
    O_U = Column(Float) 
    Line = Column(Float) 
    Team_O_U = Column(Float) 